<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            ['category_id' => 1, 'brand_id' => 2,'product_name' => 'Royal Jelly Lift Concentrate', 'product_desc' => "Perawatan selama 28 hari untuk menjaga elastisitas dan memberi kelembapan untuk kulit wajah yang kusam. Gel ini diformulasikan dengan liposom Royal Jelly, yakni bahan bernutrisi tinggi yang diproduksi oleh lebah madu yang memiliki kandungan asam amino, vitamin, dan mineral. Kaya dengan Royal Jelly CELLSPAN Complex, yakni kombinasi bahan-bahan eksklusif untuk memperkaya manfaat Royal Jelly.", 'product_composition_desc' => "Aqua, Larrea divaricata extract, Glycine soja extract, Biosaccharide Gum-1, Avena sativa kernel extract, Butylene Glycol, Lechitin, Dipropylene Glycol, Hydrolyzed Corallina officinalis, Panthenol, Hydroxyethylcellulose, Pentylene Glycol, Sodium carboxymethyl betaglucan, Diazolidinyl Urea, Iodopropynyl Butylcarbamate, Propylene Glycol, Ocimum tenuiflorum extract, Xanthan Gum, Allantoin, Trisodium EDTA, Withania somnifera flower extract, Nelumbo nucifera leaf extract, Hydrolyzed myrtus communis leaf extract, Royal Jelly, Sunflower seed oil, Lechitin, Glycerin, Fragrance, Glyceryl Polymethacrylate, Propylene Glycol" , 'product_price' => 935000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/?context=bWFzdGVyfHJvb3R8NTk1MTh8aW1hZ2UvanBlZ3xoNzEvaDJmLzkzMjY0MjY4ODIwNzguanBnfGYyNWQwNjcyZTE1NzMwMDQ2ZDU4MTc3OTI2N2M1NGI2MTVlYWRhNjI3OWU4MmVhOGU0ZDkxNDA5YjA1Y2MzN2Y"],

            ['category_id' => 1,  'brand_id' => 2,'product_name' => 'Royal Jelly Body Complex', 'product_desc' => "Mengandung teknologi microencapsulated yang secara bertahap melembabkan kulit." , 'product_composition_desc' => "Aqua, Cetearyl Alcohol, Ceteareth-20, Isopropyl Palmitate, C12-15 Alkyl Benzoate, Stearyl Stearate, Di-PPG-3 Myristyl Ether Adipate, Sodium PCA, Dimethicone, Myristyl Myristate, Bis-Diglycerylpolyacyladipate-2, Acrylates, Triethanolamine, Panthenol, Withania somnifera flower extract, Nelumbo nucifera leaf extract, DMDM hydantoin, Royal Jelly, Sunflower seed oil, Lechitin, Glycerin, Tocopheryl Acetate, Allantoin, Fragrance, Dimethylsilanol Hyaluronate, Phenoxyethanol, Potassium Sorbate, Trisodium EDTA, Polyisobutene, Hydrolyzed Myrtus communis leaf extract, Hexylene Glycol, Caprylyl Glycol",'product_price' => 600000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13027-300x300.jpg?context=bWFzdGVyfHJvb3R8Njg2MzF8aW1hZ2UvanBlZ3xoMTMvaGFjLzkzMjcxMDUzNDM1MTguanBnfGNmMTI1YTY1NTNkYTcxMDA2MWE3MjE5NTU5Y2E3Mjc1OWVlZWFmMTA4MzU4OWZhMTAxM2M3NzU1Mjk4Y2E2ZmU"],

            ['category_id' => 1,  'brand_id' => 2,'product_name' => 'RJ conditioning balm', 'product_desc' => "Formula multifungsi yang memberikan hidrasi dan extra conditioning balm dapat membantu menjaga kelembutan kulit yang kasar dan kering." , 'product_composition_desc' => "sesamum indicum seed oil, Sweet Almond ( Prunus Amygdalus Dulcis ) Oil, prunus armeniaca kernel oil, Silica Dimethyl Silylate, ricinus communis seed oil, Soybean ( Glycine Soja ) Gern Extract, Corn (Zea Mays) Starch, Silica, Oryza Sativa Bran Extract, oleic/linoleic/linolenic polyglycerides, ci 77947, Cera Alba, Shea Butter ( Butyrospermum parkii ), Theobroma Cacao (Cocoa) Seed Butter, garcinia indica seed butter, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, royal jelly extract, parfum, citral, Citronellol, Limonene, linalool",'product_price' => 209000, 'qty' => 99, 'product_img' => "hhttps://www.jafra.co.id/medias/?context=bWFzdGVyfHJvb3R8NjIyMzd8aW1hZ2UvanBlZ3xoMDYvaGZjLzkzMjcxMDU1MDczNTguanBnfDQzOTMwMzBkMDRjNmVhMDM1ODQ3ZDg0YjFiN2NmMzAyOGVhOWE3MWVkZjE4YzMwMTEzODZiODk1NTYxMDJjNGI"],

            ['category_id' => 1,  'brand_id' => 2,'product_name' => 'RJ conditioning balm', 'product_desc' => "Formula multifungsi yang memberikan hidrasi dan extra conditioning balm dapat membantu menjaga kelembutan kulit yang kasar dan kering." , 'product_composition_desc' => "sesamum indicum seed oil, Sweet Almond ( Prunus Amygdalus Dulcis ) Oil, prunus armeniaca kernel oil, Silica Dimethyl Silylate, ricinus communis seed oil, Soybean ( Glycine Soja ) Gern Extract, Corn (Zea Mays) Starch, Silica, Oryza Sativa Bran Extract, oleic/linoleic/linolenic polyglycerides, ci 77947, Cera Alba, Shea Butter ( Butyrospermum parkii ), Theobroma Cacao (Cocoa) Seed Butter, garcinia indica seed butter, Tocopherol, Helianthus Annuus (Sunflower) Seed Oil, royal jelly extract, parfum, citral, Citronellol, Limonene, linalool",'product_price' => 209000, 'qty' => 99, 'product_img' => "hhttps://www.jafra.co.id/medias/?context=bWFzdGVyfHJvb3R8NjIyMzd8aW1hZ2UvanBlZ3xoMDYvaGZjLzkzMjcxMDU1MDczNTguanBnfDQzOTMwMzBkMDRjNmVhMDM1ODQ3ZDg0YjFiN2NmMzAyOGVhOWE3MWVkZjE4YzMwMTEzODZiODk1NTYxMDJjNGI"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'ROYAL REVITALIZE GENTLE CLEANSING MILK', 'product_desc' => "Membantu membersihkan make up, minyak, dan sisa kotoran yang menempel pada wajah . | 125 ml" , 'product_composition_desc' => "Water/Aqua, Acrylates Copolymer, Decyl Glucoside, Cocamidopropyl Betaine, PEG-7 Glyceryl Cocoate, Coco-Glucoside, Styrene/Acrylates Copolymer, Sodium Lauroyl Sarcosinate, Sodium Hydroxide, Glycol Stearate, Phenoxyethanol, Benzoic Acid, Dehydroacetic Acid, Allantoin, Tetrasodium EDTA, Fragrance /Parfum, Benzyl Salicylate, Limonene, Hydroxycitronellal, Butylphenyl Methylpropional (Lillial), Linalool, Caprylyl Glycol, Sodium Ascorbyl Phosphate, Glycerin, Polygonum Aviculare Extract, Tetrapeptide-45, Hydrogenated Lecithin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin, Lecithin, Dipropylene Glycol, Royal Jelly, 2-Phenoxyethanol, Royal Jelly Powder",'product_price' => 307000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13103-300x300.jpg?context=bWFzdGVyfHJvb3R8MzYyNDh8aW1hZ2UvanBlZ3xoMDYvaDIyLzkzMjgyMTkxNjA2MDYuanBnfGQ1NTk1YjFhZDdhODUwYmViZGNlYzZmZGQwZDNjMWFiZWIwNjU1NWY1NzA5MmVlOTc1ZGJmNTkzNmQwMzA2ZDc"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'REVITALIZE LONGEVITY BALM', 'product_desc' => "Membantu menjaga elastisitas kulit wajah, menghaluskan, dan meminimalisir tanda-tanda penuaan, seperti garis-garis halus dan pori-pori yang tampak di permukaan wajah." , 'product_composition_desc' => "Aqua, Hydroxyethyl Acrylate/ Sodium Acryloyldimethyltaurate Copolymer, Squalane, Polysorbate 60, Caprylic/Capric Triglyceride, Butyrospermum Parkii (Shea) Butter, Pentylene Glycol, C12-15 Alkyl Benzoate, Palmitoyl Glycine, Polyacrylamide, C13-14 Isoparaffin, Laureth-7, Medicago (Alfalfa) sativa extract, Cocos (Coconut) nucifera oil, Tetrapeptide-45, Hydrogenated Lecithin, Glycerin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin, Cyclomethicone, Dimethiconol, DMDM Hydantoin, Trisodium EDTA Royal Jelly Powder PEG-4 Laurate, Iodopropynyl Butylcarbamate, Polyethylene glycol, PEG-4 Dilaurate, Lecithin, Dipropylene Glycol, Royal Jelly, 2-Phenoxyethanol, Honey, Retinyl Palmitate ,Sodium Ascorbyl Phosphate, Tocopherol, Fragrance",'product_price' => 716000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13102-300x300.jpg?context=bWFzdGVyfHJvb3R8MzY2Mzd8aW1hZ2UvanBlZ3xoYTQvaGQwLzkxMTE3NzMyNDk1NjYuanBnfGFjMjFmODhkZDAyZTA2MDUzYjg3ZDY3YWRkMzU4NDdhMWQ3YTA2NjdlZjA0YzBmNzJhOWI1MzYxZDZiYTIzZGY"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'Revitalize Extra Hydration Serum', 'product_desc' => "Membantu memberikan asupan serum dalam jumlah cukup untuk jenis kulit kering, serta membantu menyamarkan tanda-tanda penuaan pada kulit wajah.  " , 'product_composition_desc' => "Aqua, Ophiopogon Japonicus root Extract, Glycerin, Octyldodecanol, Isosorbide Dicaprylate, Carrageenan, Sea Salt, Sodium Hyaluronate, Trehalose, Sodium PCA, Polyquaternium-51, Urea, Triacetin, Sodium Polyacrylate, Biosaccharide Gum-1, Xylitol, Xylitylglucoside, Anhydroxylitol, Tocopherol, DMDM Hydantoin, Iodopropynyl Butylcarbamate, Cocos Nucifera Fruit Extract, Moringa Oleifera Leaf Extract, Trisodium EDTA, Royal Jelly Powder, Tetrapeptide-45, Hydrogenated Lecithin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin, Lecithin, Dipropylene Glycol, Royal Jelly, 2-Phenoxyethanol, Fragrance",'product_price' => 459000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13100-300x300.jpg?context=bWFzdGVyfHJvb3R8NDQxOTR8aW1hZ2UvanBlZ3xoZGIvaDM4LzkwODE5MDM1NDYzOTguanBnfDQ5YjJiODkwNGI0YWQ2MmU2MDc0MzNmMTliMDhlNzU5NjE2Mjg4MTRmNGI3MzYxZWY1NWQ5ZWI1YmY3MDQyOGY"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'Revitalize Line & Pore Perfecting Serum', 'product_desc' => "Membantu menjaga kulit agar tetap terasa lembut, sekaligus membantu menyamarkan garis halus dan pori-pori pada wajah.  " , 'product_composition_desc' => "Aqua, Silica, Glycerin, Trisodium EDTA, DMDM Hydantoin, Ethylhexyl Palmitate, Silica Dimethyl Silylate, Butylene Glycol, Sodium Hyaluronate, PEG-4 Laurate, Iodopropynyl Butylcarbamate, Polyethylene glycol, PEG-4 Dilaurate, Glycerin, Macrocystis Pyrifera Extract, PVP, Hydrolyzed Vegetable Protein, Sodium Hyaluronate, Trehalose, Sodium PCA, Polyquaternium-51, Urea, Triacetin, Sodium Polyacrylate, Dimethicone, Cyclopentasiloxane, Trideceth-6, PEG/PPG 18/18 Dimethicone, Adipic Acid/Neopentyl Glycol Crosspolymer, VP/VA Copolymer, Hydroxypropyl Methylcellulose, Amodimethicone, Royal Jelly Powder, Tetrapeptide-45, Hydrogenated Lecithin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin, Lecithin, Dipropylene Glycol, Royal Jelly,2-Phenoxyethanol, Fragrance, Retinyl Palmitate",'product_price' => 459000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13106-300x300.jpg?context=bWFzdGVyfHJvb3R8NDE4Mjh8aW1hZ2UvanBlZ3xoMjIvaDg4LzkwODE4MjgxNDcyMzAuanBnfGVjYmQwYWRkNDI4NDQyMTg5YmU2MjJlN2Q1NzcxYTE4MDE1N2M5NzY0MDE4NDQwMDI2NDczNTI5MzBiOWE4Mzg"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'REVITALIZE Spot Serum', 'product_desc' => "Membantu agar warna kulit tampak merata serta membuat wajah tampak cerah." , 'product_composition_desc' => "Aqua, Glycerin, Octyldodecanol, Butylene Glycol, Actinidia Chinensis (Kiwi) Fruit Water, Alcohol, Sophora Flavescens Root Extract, Lepidium Sativum Sprout Extract, Lecithin, Phenoxyethanol, Biosaccharide Gum-1, Sodium Polyacrylate, DMDM Hydantoin, Iodopropynyl Butylcarbamate, Cocos Nucifera Fruit Extract, Moringa Oleifera Leaf Extract, Royal Jelly Powder, Trisodium EDTA, Sodium Ascorbyl Phosphate, Tetrapeptide-45, Hydrogenated Lecithin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin, Dipropylene Glycol, Royal Jelly, 2-Phenoxyethanol, Fragrance.",'product_price' => 459000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13105-300x300.jpg?context=bWFzdGVyfHJvb3R8NDYzMTB8aW1hZ2UvanBlZ3xoYTQvaGNkLzkxMjk4NjcwODM4MDYuanBnfGIyNDBkMDQ3ZjI5NThkOThkNzg5NTNmNDVjMjZhMjcxMDU4Yzk0YTY3NzEzNTVlYjMxZmNlMTRmOGU1ZDY1YmQ"],

            ['category_id' => 1,  'brand_id' => 3,'product_name' => 'Revitalize Volcanic Micro Polish Mask', 'product_desc' => "Membantu mengurangi minyak berlebih sehingga dapat membantu meawat kulit wajah yang kusam, membantu proses regenerasi kuliy, sekaligus memberikan nutrisi pada kulit agar tampak lembut, lembap, cerah, kenyal, dan elastis." , 'product_composition_desc' => "Aqua, Silica, Helianthus Annuus Oil, Glyceryl Stearate, PEG-100 Stearate, Synthetic Wax, Cetyl Alcohol, Cellulose, Sorbitan Stearate, Glycerin, Dimethicone, Phenoxyethanol, Caprylyl Glycol, Potassium Sorbate, Hexylene Glycol, Charcoal Powder, Papaya Fruit Ferment Extract, Radish Root Ferment Filtrate, Volcanic Rock, Coco-Caprylate/Caprate, Guar Hydroxypropyltrimonium Chloride, Allantoin, Fragrance, Trisodium EDTA, Bisabolol, Tocopheryl Acetate, Ascorbyl Palmitate, Triethanolamine , Royal Jelly Powder, Lecithin, Dipropylene Glycol, Royal Jelly, 2-Phenoxyethanol, Tetrapeptide-45, Hydrogenated Lecithin, Butyrospermum Parkii (Shea) Butter, Phenethyl Alcohol, Ethylhexylglycerin, Maltodextrin",'product_price' => 409000, 'qty' => 99, 'product_img' => "https://www.jafra.co.id/medias/13107-300x300.jpg?context=bWFzdGVyfHJvb3R8MzgyMTV8aW1hZ2UvanBlZ3xoODkvaDQwLzkwNTY2Nzc0MjkyNzguanBnfDQxYmFjNDg0Yjc2Y2U1Zjg4MTgzMzk3MGQyM2Q5NmUwNjJhMmMwODRiZmQ3N2ZmYTVmMTFiYTQ3NTlhMTU5YjI"],
        );

        DB::table('products')->insertOrIgnore($data);
    }
}
